services:
  wanderlust:
    image: ghcr.io/therepos/wanderlust:latest
    container_name: wanderlust
    restart: unless-stopped
    ports:
      - "8099:8000"
    volumes:
      - wanderlust-data:/data
    environment:
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}

volumes:
  wanderlust-data:
